INSERT INTO department (department_name)
VALUES  ('Marketing'),
        ('Finance'),
        ('Operations'),
        ('Human Resourses'),
        ('IT');

INSERT INTO roles (title, salary, department_id)
VALUES  ('Marketing Manager', 80000, 1),
        ('Visual Designer', 60000, 1),
        ('Data Analyst', 50000, 1),
        ('SEO Strategist', 55000, 1),
        ('Accountant', 55000, 2),
        ('Auditor', 42000, 2),
        ('Finance Manager', 43000, 2),
        ('Budget Analyst', 50000, 2),
        ('Operations Coordinator', 45000, 3),
        ('Operations Analyst', 56000, 3),
        ('Operations Director', 70000, 3),
        ('Project Manager', 65000, 3),
        ('HR Coordinator', 60000, 4),
        ('HR Administrator', 52000, 4),
        ('HR Manager', 68000, 4),
        ('HR Director', 72000, 4),
        ('Hardware Technician', 48000, 5),
        ('IT Project Manager', 66000, 5),
        ('Network Administrator', 58000, 5),
        ('IT Director', 1000000, 5);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ('Shawn', 'Miller', 20, null),
        ('Casey', 'Miller', 1, null),
        ('Connor', 'Miller', 11, null),
        ('Kristi', 'Miller', 16, null),
        ('Boo', 'Miller', 7, null),
        ('John', 'Doesntcare', 12, 3),
        ('Tod', 'Criesalot', 8, 5),
        ('Beth', 'Hatesherjob', 5, 5),
        ('Ashley', 'Loveslife', 6, 5),
        ('Bill', 'Duck', 2, 2),
        ('Jennifer', 'Thompson', 19, 1),
        ('Stiches', 'Hurt', 3, 2),
        ('Mickey', 'Mouse', 17, 1),
        ('Scobby', 'Doo', 4, 2),
        ('Harry', 'Potter', 13, 4),
        ('Red', 'Toad', 18, 1),
        ('Teddy', 'Ruxpin', 9, 3),
        ('He', 'Man', 10, 3),
        ('G.I.', 'Joe', 14, 4),
        ('Free', 'Guy', 15, 4);